language: rust

rust:
  #- stable ## Let's spare Travis
 - nightly

addons:
  apt:
    update: true

before_install:
 - sudo apt-get install -y ninja-build python3-pip
 - pip3 install meson
 - wget https://code.videolan.org/videolan/dav1d/-/archive/0.1.0/dav1d-0.1.0.tar.gz
 - tar -xvf dav1d-0.1.0.tar.gz
 - cd dav1d-0.1.0
 - meson .build
 - ninja -C .build
 - sudo ninja -C .build install
 - git submodule update --init --recursive

script: 
 - cargo build --release --verbose
 - cargo test --verbose
 
